version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: mi_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - netmetabase

  metabase:
    image: metabase/metabase
    container_name: mi_metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=${POSTGRES_DB}
      - MB_DB_PORT=5432
      - MB_DB_USER=${POSTGRES_USER}
      - MB_DB_PASS=${POSTGRES_PASSWORD}
      - MB_DB_HOST=postgres
    ports:
      - "3000:3000"
    networks:
      - netmetabase
    depends_on:
      - postgres

networks:
  netmetabase:
    driver: bridge
